# Generated by Django 6.0.1 on 2026-01-20 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=125)),
                ('feed_type', models.CharField(max_length=125)),
                ('price', models.IntegerField()),
                ('exp_date', models.CharField(max_length=125)),
                ('quantity_available', models.IntegerField()),
                ('thumb_nail', models.ImageField(blank=True, null=True, upload_to='server_images/')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('delivery_location', models.CharField(max_length=125)),
                ('status', models.CharField(max_length=125)),
                ('created_at', models.DateField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fish_feed.product')),
            ],
        ),
    ]
