# Generated by Django 6.0.1 on 2026-01-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_feed', '0002_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumb_nail',
            new_name='product_thumbnail',
        ),
    ]
