# Generated by Django 6.0.1 on 2026-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_feed', '0003_rename_thumb_nail_product_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='production_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
