# Generated by Django 6.0.1 on 2026-01-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_feed', '0004_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='production_description',
            new_name='product_description',
        ),
    ]
